### ISSUE TITLE
Platform Selection

### ISSUE THREAD

**Issue by cavaevinci** [cavaevinci/Gamester#3]
- Implement UI for Platform selection View
- Make sure its first screen user sees when app is installed and runned for the first time
- Adjust API calls to make sure plaform id is included into calls
- Make sure user cant get past that screen if he doesnt select at least 1 platform

**Comment by ErikEmciDurkan** [comment]
- make sure on platform selection view user selection is saved into user defaults
- read api documentation to see how to use platforms in api call to get genres and games
- this screen appears in settings screen alongside genre picker in settings view
-
